name: event-triggers-example.
on:
  push:
    branches: 
      - 'main'
    tags:
      - '*'
    paths:
      - '.github/workflows/02-event-triggers.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/02-event-triggers.yml'
  schedule:
    - cron: '*/45 9-12 * * 1,4'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print current path
        working-directory: ./02-event-triggers
        run: pwd

      - name: Event
        run: echo "Triggered by $GITHUB_EVENT_NAME"

      - name: Say Hello
        run: echo "Hello world!"
